"""add_broadcast_system_tables

Revision ID: 05dc671d7118
Revises: 53e61c719b14
Create Date: 2025-12-07 13:37:46.908298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05dc671d7118'
down_revision: Union[str, Sequence[str], None] = '53e61c719b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('photo_file_id', sa.String(length=255), nullable=True),
    sa.Column('video_file_id', sa.String(length=255), nullable=True),
    sa.Column('buttons', sa.JSON(), nullable=True),
    sa.Column('target_type', sa.Enum('ALL', 'ACTIVE', 'INACTIVE', 'WITH_BALANCE', 'WITH_PETS', 'WITH_DEPOSITS', 'BY_LANGUAGE', 'BY_REGISTRATION', 'CUSTOM', name='broadcasttargettype'), nullable=False),
    sa.Column('min_balance', sa.Numeric(), nullable=True),
    sa.Column('max_balance', sa.Numeric(), nullable=True),
    sa.Column('has_pets', sa.Boolean(), nullable=True),
    sa.Column('min_pets_count', sa.Integer(), nullable=True),
    sa.Column('has_deposits', sa.Boolean(), nullable=True),
    sa.Column('min_deposit_total', sa.Numeric(), nullable=True),
    sa.Column('registered_after', sa.DateTime(), nullable=True),
    sa.Column('registered_before', sa.DateTime(), nullable=True),
    sa.Column('language_codes', sa.JSON(), nullable=True),
    sa.Column('custom_user_ids', sa.JSON(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'SENDING', 'COMPLETED', 'CANCELLED', 'FAILED', name='broadcaststatus'), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('delivered_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('blocked_count', sa.Integer(), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_broadcasts_created_at', 'broadcasts', ['created_at'], unique=False)
    op.create_index('idx_broadcasts_scheduled_at', 'broadcasts', ['scheduled_at'], unique=False)
    op.create_index('idx_broadcasts_status', 'broadcasts', ['status'], unique=False)
    op.create_table('broadcast_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broadcast_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_broadcast_logs_broadcast_id', 'broadcast_logs', ['broadcast_id'], unique=False)
    op.create_index('idx_broadcast_logs_sent', 'broadcast_logs', ['sent'], unique=False)
    op.create_index('idx_broadcast_logs_user_id', 'broadcast_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_broadcast_logs_user_id', table_name='broadcast_logs')
    op.drop_index('idx_broadcast_logs_sent', table_name='broadcast_logs')
    op.drop_index('idx_broadcast_logs_broadcast_id', table_name='broadcast_logs')
    op.drop_table('broadcast_logs')
    op.drop_index('idx_broadcasts_status', table_name='broadcasts')
    op.drop_index('idx_broadcasts_scheduled_at', table_name='broadcasts')
    op.drop_index('idx_broadcasts_created_at', table_name='broadcasts')
    op.drop_table('broadcasts')
    # ### end Alembic commands ###
