"""Add boost system tables

Revision ID: 958018a7a883
Revises: i9400h920g6e
Create Date: 2025-12-05 21:25:28.843904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958018a7a883'
down_revision: Union[str, Sequence[str], None] = 'i9400h920g6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new TxType enum values
    op.execute("ALTER TYPE txtype ADD VALUE IF NOT EXISTS 'boost_purchase'")
    op.execute("ALTER TYPE txtype ADD VALUE IF NOT EXISTS 'auto_claim_commission'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_claim_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('cost_xpet', sa.Numeric(), nullable=False),
    sa.Column('commission_percent', sa.Numeric(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_claims', sa.Integer(), nullable=False),
    sa.Column('total_commission', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auto_claim_expires_at', 'auto_claim_subscriptions', ['expires_at'], unique=False)
    op.create_index('idx_auto_claim_user_id', 'auto_claim_subscriptions', ['user_id'], unique=False)
    op.create_table('boost_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('boost_type', sa.Enum('ROI_BOOST', 'SNACK', 'AUTO_CLAIM', name='boosttype'), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('amount_xpet', sa.Numeric(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['user_pets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_boost_tx_type', 'boost_transactions', ['boost_type'], unique=False)
    op.create_index('idx_boost_tx_user_id', 'boost_transactions', ['user_id'], unique=False)
    op.create_table('pet_roi_boosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('boost_percent', sa.Numeric(), nullable=False),
    sa.Column('extra_profit', sa.Numeric(), nullable=False),
    sa.Column('cost_xpet', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['user_pets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pet_roi_boosts_pet_id', 'pet_roi_boosts', ['pet_id'], unique=False)
    op.create_index('idx_pet_roi_boosts_user_id', 'pet_roi_boosts', ['user_id'], unique=False)
    op.create_table('pet_snacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snack_type', sa.Enum('COOKIE', 'STEAK', 'CAKE', name='snacktype'), nullable=False),
    sa.Column('bonus_percent', sa.Numeric(), nullable=False),
    sa.Column('cost_xpet', sa.Numeric(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['user_pets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pet_snacks_pet_id', 'pet_snacks', ['pet_id'], unique=False)
    op.create_index('idx_pet_snacks_user_id', 'pet_snacks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pet_snacks_user_id', table_name='pet_snacks')
    op.drop_index('idx_pet_snacks_pet_id', table_name='pet_snacks')
    op.drop_table('pet_snacks')
    op.drop_index('idx_pet_roi_boosts_user_id', table_name='pet_roi_boosts')
    op.drop_index('idx_pet_roi_boosts_pet_id', table_name='pet_roi_boosts')
    op.drop_table('pet_roi_boosts')
    op.drop_index('idx_boost_tx_user_id', table_name='boost_transactions')
    op.drop_index('idx_boost_tx_type', table_name='boost_transactions')
    op.drop_table('boost_transactions')
    op.drop_index('idx_auto_claim_user_id', table_name='auto_claim_subscriptions')
    op.drop_index('idx_auto_claim_expires_at', table_name='auto_claim_subscriptions')
    op.drop_table('auto_claim_subscriptions')
    # ### end Alembic commands ###
