"""initial

Revision ID: dbcc0a67b7cd
Revises: 
Create Date: 2025-12-05 03:26:42.008928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbcc0a67b7cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('base_price', sa.Numeric(), nullable=False),
    sa.Column('daily_rate', sa.Numeric(), nullable=False),
    sa.Column('roi_cap_multiplier', sa.Numeric(), nullable=False),
    sa.Column('level_prices', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reward_xpet', sa.Numeric(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('task_type', sa.Enum('TELEGRAM_CHANNEL', 'TELEGRAM_CHAT', 'TWITTER', 'DISCORD', 'WEBSITE', 'OTHER', name='tasktype'), nullable=False),
    sa.Column('verification_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_active', 'tasks', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('balance_xpet', sa.Numeric(), nullable=False),
    sa.Column('ref_code', sa.String(length=10), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=True),
    sa.Column('ref_levels_unlocked', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_code'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index('idx_users_ref_code', 'users', ['ref_code'], unique=False)
    op.create_index('idx_users_referrer_id', 'users', ['referrer_id'], unique=False)
    op.create_index('idx_users_telegram_id', 'users', ['telegram_id'], unique=False)
    op.create_table('deposit_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('network', sa.Enum('BEP20', 'SOLANA', 'TON', name='networktype'), nullable=False),
    sa.Column('deposit_address', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deposit_requests_status', 'deposit_requests', ['status'], unique=False)
    op.create_table('referral_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('claim_amount', sa.Numeric(), nullable=False),
    sa.Column('reward_amount', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('level >= 1 AND level <= 5', name='check_level_range'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_referral_rewards_from_user', 'referral_rewards', ['from_user_id'], unique=False)
    op.create_index('idx_referral_rewards_to_user', 'referral_rewards', ['to_user_id'], unique=False)
    op.create_table('referral_stats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level_1_count', sa.Integer(), nullable=False),
    sa.Column('level_2_count', sa.Integer(), nullable=False),
    sa.Column('level_3_count', sa.Integer(), nullable=False),
    sa.Column('level_4_count', sa.Integer(), nullable=False),
    sa.Column('level_5_count', sa.Integer(), nullable=False),
    sa.Column('level_1_earned', sa.Numeric(), nullable=False),
    sa.Column('level_2_earned', sa.Numeric(), nullable=False),
    sa.Column('level_3_earned', sa.Numeric(), nullable=False),
    sa.Column('level_4_earned', sa.Numeric(), nullable=False),
    sa.Column('level_5_earned', sa.Numeric(), nullable=False),
    sa.Column('total_earned', sa.Numeric(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAW', 'CLAIM', 'REF_REWARD', 'TASK_REWARD', 'SELL_REFUND', 'ADMIN_ADJUST', 'PET_BUY', 'PET_UPGRADE', name='txtype'), nullable=False),
    sa.Column('amount_xpet', sa.Numeric(), nullable=False),
    sa.Column('fee', sa.Numeric(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='txstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transactions_type', 'transactions', ['type'], unique=False)
    op.create_index('idx_transactions_user_id', 'transactions', ['user_id'], unique=False)
    op.create_table('user_pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pet_type_id', sa.Integer(), nullable=False),
    sa.Column('invested_total', sa.Numeric(), nullable=False),
    sa.Column('level', sa.Enum('BABY', 'ADULT', 'MYTHIC', name='petlevel'), nullable=False),
    sa.Column('status', sa.Enum('OWNED_IDLE', 'TRAINING', 'READY_TO_CLAIM', 'EVOLVED', 'SOLD', name='petstatus'), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('profit_claimed', sa.Numeric(), nullable=False),
    sa.Column('training_started_at', sa.DateTime(), nullable=True),
    sa.Column('training_ends_at', sa.DateTime(), nullable=True),
    sa.Column('evolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_type_id'], ['pet_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_pets_status', 'user_pets', ['status'], unique=False)
    op.create_index('idx_user_pets_user_id', 'user_pets', ['user_id'], unique=False)
    op.create_table('user_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='taskstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'task_id', name='uq_user_task')
    )
    op.create_index('idx_user_tasks_user_id', 'user_tasks', ['user_id'], unique=False)
    op.create_table('withdraw_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('fee', sa.Numeric(), nullable=False),
    sa.Column('network', sa.Enum('BEP20', 'SOLANA', 'TON', name='networktype'), nullable=False),
    sa.Column('wallet_address', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_withdraw_requests_status', 'withdraw_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_withdraw_requests_status', table_name='withdraw_requests')
    op.drop_table('withdraw_requests')
    op.drop_index('idx_user_tasks_user_id', table_name='user_tasks')
    op.drop_table('user_tasks')
    op.drop_index('idx_user_pets_user_id', table_name='user_pets')
    op.drop_index('idx_user_pets_status', table_name='user_pets')
    op.drop_table('user_pets')
    op.drop_index('idx_transactions_user_id', table_name='transactions')
    op.drop_index('idx_transactions_type', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('referral_stats')
    op.drop_index('idx_referral_rewards_to_user', table_name='referral_rewards')
    op.drop_index('idx_referral_rewards_from_user', table_name='referral_rewards')
    op.drop_table('referral_rewards')
    op.drop_index('idx_deposit_requests_status', table_name='deposit_requests')
    op.drop_table('deposit_requests')
    op.drop_index('idx_users_telegram_id', table_name='users')
    op.drop_index('idx_users_referrer_id', table_name='users')
    op.drop_index('idx_users_ref_code', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_tasks_active', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('pet_types')
    # ### end Alembic commands ###
